### ISSUE TITLE
Notification delete

### ISSUE THREAD

**Issue by lucnap** [infobip/push-plugin-cordova-phonegap#6]
How to delete a notification?
It could be nice something like  "push.delete(notificationId)"

**Comment by mmiroslav** [comment]
Hi Luciano,
What do you mean, when say "delete notification"? Do you want to hide it from notification bar or something else?

**Comment by lucnap** [comment]
Yes, want to hide from the notification bar.
Right now it is automatically removed when you open the notification, but can be very useful to do it programmatically.

**Comment by mmiroslav** [comment]
Hi Luciano,

We didn't implemented that feature in current version of Push Plugin, but it is planned for next major release.
Also current version, has iOS specific function to dismiss all notifications from notification tray. Here is code: `push.cancelAllNotifications()`

Stay tuned...
